/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thnet_airbraketest_serialport */

#ifndef _Included_com_thnet_airbraketest_serialport
#define _Included_com_thnet_airbraketest_serialport
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_thnet_airbraketest_serialport
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_thnet_tailairbrakingtest_serialport_SerialPort_open
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_thnet_airbraketest_serialport
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_thnet_tailairbrakingtest_serialport_SerialPort_close
  (JNIEnv *, jobject);

/*
*Class : com_thnet_airbraketest_serialport
*Method : tcflush
*Signature ()V
*/
JNIEXPORT void JNICALL Java_com_thnet_tailairbrakingtest_serialport_SerialPort_tcflush
        (JNIEnv *env, jobject thiz);
#ifdef __cplusplus
}
#endif
#endif
