package com.thnet.tailairbrakingtest.DAO;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.thnet.tailairbrakingtest.DAO.PressureValue;
import com.thnet.tailairbrakingtest.DAO.SysParms;
import com.thnet.tailairbrakingtest.DAO.TestDetail;
import com.thnet.tailairbrakingtest.DAO.TestWindContent;
import com.thnet.tailairbrakingtest.DAO.UserInfo;

import com.thnet.tailairbrakingtest.DAO.PressureValueDao;
import com.thnet.tailairbrakingtest.DAO.SysParmsDao;
import com.thnet.tailairbrakingtest.DAO.TestDetailDao;
import com.thnet.tailairbrakingtest.DAO.TestWindContentDao;
import com.thnet.tailairbrakingtest.DAO.UserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pressureValueDaoConfig;
    private final DaoConfig sysParmsDaoConfig;
    private final DaoConfig testDetailDaoConfig;
    private final DaoConfig testWindContentDaoConfig;
    private final DaoConfig userInfoDaoConfig;

    private final PressureValueDao pressureValueDao;
    private final SysParmsDao sysParmsDao;
    private final TestDetailDao testDetailDao;
    private final TestWindContentDao testWindContentDao;
    private final UserInfoDao userInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pressureValueDaoConfig = daoConfigMap.get(PressureValueDao.class).clone();
        pressureValueDaoConfig.initIdentityScope(type);

        sysParmsDaoConfig = daoConfigMap.get(SysParmsDao.class).clone();
        sysParmsDaoConfig.initIdentityScope(type);

        testDetailDaoConfig = daoConfigMap.get(TestDetailDao.class).clone();
        testDetailDaoConfig.initIdentityScope(type);

        testWindContentDaoConfig = daoConfigMap.get(TestWindContentDao.class).clone();
        testWindContentDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        pressureValueDao = new PressureValueDao(pressureValueDaoConfig, this);
        sysParmsDao = new SysParmsDao(sysParmsDaoConfig, this);
        testDetailDao = new TestDetailDao(testDetailDaoConfig, this);
        testWindContentDao = new TestWindContentDao(testWindContentDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);

        registerDao(PressureValue.class, pressureValueDao);
        registerDao(SysParms.class, sysParmsDao);
        registerDao(TestDetail.class, testDetailDao);
        registerDao(TestWindContent.class, testWindContentDao);
        registerDao(UserInfo.class, userInfoDao);
    }
    
    public void clear() {
        pressureValueDaoConfig.clearIdentityScope();
        sysParmsDaoConfig.clearIdentityScope();
        testDetailDaoConfig.clearIdentityScope();
        testWindContentDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
    }

    public PressureValueDao getPressureValueDao() {
        return pressureValueDao;
    }

    public SysParmsDao getSysParmsDao() {
        return sysParmsDao;
    }

    public TestDetailDao getTestDetailDao() {
        return testDetailDao;
    }

    public TestWindContentDao getTestWindContentDao() {
        return testWindContentDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

}
