package com.thnet.tailairbrakingtest.DAO;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PressureValue".
*/
public class PressureValueDao extends AbstractDao<PressureValue, Long> {

    public static final String TABLENAME = "PressureValue";

    /**
     * Properties of entity PressureValue.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "id");
        public final static Property TestID = new Property(1, String.class, "testID", false, "TestID");
        public final static Property PressureTime = new Property(2, String.class, "pressureTime", false, "PressureTime");
        public final static Property PressureValue = new Property(3, int.class, "pressureValue", false, "PressureValue");
        public final static Property HeadPressureValue = new Property(4, int.class, "headPressureValue", false, "HeadPressureValue");
        public final static Property SourcePressureValue = new Property(5, int.class, "sourcePressureValue", false, "SourcePressureValue");
        public final static Property CenterPressureValue = new Property(6, int.class, "centerPressureValue", false, "CenterPressureValue");
        public final static Property BoxTemperature = new Property(7, int.class, "boxTemperature", false, "BoxTemperature");
        public final static Property BoxHumidity = new Property(8, int.class, "boxHumidity", false, "BoxHumidity");
        public final static Property PressureKeepMinutes = new Property(9, int.class, "pressureKeepMinutes", false, "PressureKeepMinutes");
        public final static Property TailPressureState1 = new Property(10, int.class, "tailPressureState1", false, "TailPressureState1");
        public final static Property TailPressureState2 = new Property(11, int.class, "tailPressureState2", false, "TailPressureState2");
        public final static Property TailPressureValue1 = new Property(12, int.class, "tailPressureValue1", false, "TailPressureValue1");
        public final static Property TailPressureValue2 = new Property(13, int.class, "tailPressureValue2", false, "TailPressureValue2");
        public final static Property PressureSourceOrTotal = new Property(14, int.class, "pressureSourceOrTotal", false, "PressureSourceOrTotal");
        public final static Property TestResult = new Property(15, int.class, "testResult", false, "TestResult");
    }


    public PressureValueDao(DaoConfig config) {
        super(config);
    }
    
    public PressureValueDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PressureValue entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String testID = entity.getTestID();
        if (testID != null) {
            stmt.bindString(2, testID);
        }
 
        String pressureTime = entity.getPressureTime();
        if (pressureTime != null) {
            stmt.bindString(3, pressureTime);
        }
        stmt.bindLong(4, entity.getPressureValue());
        stmt.bindLong(5, entity.getHeadPressureValue());
        stmt.bindLong(6, entity.getSourcePressureValue());
        stmt.bindLong(7, entity.getCenterPressureValue());
        stmt.bindLong(8, entity.getBoxTemperature());
        stmt.bindLong(9, entity.getBoxHumidity());
        stmt.bindLong(10, entity.getPressureKeepMinutes());
        stmt.bindLong(11, entity.getTailPressureState1());
        stmt.bindLong(12, entity.getTailPressureState2());
        stmt.bindLong(13, entity.getTailPressureValue1());
        stmt.bindLong(14, entity.getTailPressureValue2());
        stmt.bindLong(15, entity.getPressureSourceOrTotal());
        stmt.bindLong(16, entity.getTestResult());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PressureValue entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String testID = entity.getTestID();
        if (testID != null) {
            stmt.bindString(2, testID);
        }
 
        String pressureTime = entity.getPressureTime();
        if (pressureTime != null) {
            stmt.bindString(3, pressureTime);
        }
        stmt.bindLong(4, entity.getPressureValue());
        stmt.bindLong(5, entity.getHeadPressureValue());
        stmt.bindLong(6, entity.getSourcePressureValue());
        stmt.bindLong(7, entity.getCenterPressureValue());
        stmt.bindLong(8, entity.getBoxTemperature());
        stmt.bindLong(9, entity.getBoxHumidity());
        stmt.bindLong(10, entity.getPressureKeepMinutes());
        stmt.bindLong(11, entity.getTailPressureState1());
        stmt.bindLong(12, entity.getTailPressureState2());
        stmt.bindLong(13, entity.getTailPressureValue1());
        stmt.bindLong(14, entity.getTailPressureValue2());
        stmt.bindLong(15, entity.getPressureSourceOrTotal());
        stmt.bindLong(16, entity.getTestResult());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PressureValue readEntity(Cursor cursor, int offset) {
        PressureValue entity = new PressureValue( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // testID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // pressureTime
            cursor.getInt(offset + 3), // pressureValue
            cursor.getInt(offset + 4), // headPressureValue
            cursor.getInt(offset + 5), // sourcePressureValue
            cursor.getInt(offset + 6), // centerPressureValue
            cursor.getInt(offset + 7), // boxTemperature
            cursor.getInt(offset + 8), // boxHumidity
            cursor.getInt(offset + 9), // pressureKeepMinutes
            cursor.getInt(offset + 10), // tailPressureState1
            cursor.getInt(offset + 11), // tailPressureState2
            cursor.getInt(offset + 12), // tailPressureValue1
            cursor.getInt(offset + 13), // tailPressureValue2
            cursor.getInt(offset + 14), // pressureSourceOrTotal
            cursor.getInt(offset + 15) // testResult
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PressureValue entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTestID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPressureTime(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPressureValue(cursor.getInt(offset + 3));
        entity.setHeadPressureValue(cursor.getInt(offset + 4));
        entity.setSourcePressureValue(cursor.getInt(offset + 5));
        entity.setCenterPressureValue(cursor.getInt(offset + 6));
        entity.setBoxTemperature(cursor.getInt(offset + 7));
        entity.setBoxHumidity(cursor.getInt(offset + 8));
        entity.setPressureKeepMinutes(cursor.getInt(offset + 9));
        entity.setTailPressureState1(cursor.getInt(offset + 10));
        entity.setTailPressureState2(cursor.getInt(offset + 11));
        entity.setTailPressureValue1(cursor.getInt(offset + 12));
        entity.setTailPressureValue2(cursor.getInt(offset + 13));
        entity.setPressureSourceOrTotal(cursor.getInt(offset + 14));
        entity.setTestResult(cursor.getInt(offset + 15));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PressureValue entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PressureValue entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PressureValue entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
