package com.thnet.tailairbrakingtest.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PressureValue".
*/
public class PressureValueDao extends AbstractDao<PressureValue, Long> {

    public static final String TABLENAME = "PressureValue";

    /**
     * Properties of entity PressureValue.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "id");
        public final static Property TestID = new Property(1, String.class, "testID", false, "TestID");
        public final static Property PressureTime = new Property(2, String.class, "pressureTime", false, "PressureTime");
        public final static Property PressureValue = new Property(3, int.class, "pressureValue", false, "PressureValue");
    }


    public PressureValueDao(DaoConfig config) {
        super(config);
    }
    
    public PressureValueDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PressureValue entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String testID = entity.getTestID();
        if (testID != null) {
            stmt.bindString(2, testID);
        }
 
        String pressureTime = entity.getPressureTime();
        if (pressureTime != null) {
            stmt.bindString(3, pressureTime);
        }
        stmt.bindLong(4, entity.getPressureValue());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PressureValue entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String testID = entity.getTestID();
        if (testID != null) {
            stmt.bindString(2, testID);
        }
 
        String pressureTime = entity.getPressureTime();
        if (pressureTime != null) {
            stmt.bindString(3, pressureTime);
        }
        stmt.bindLong(4, entity.getPressureValue());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PressureValue readEntity(Cursor cursor, int offset) {
        PressureValue entity = new PressureValue( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // testID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // pressureTime
            cursor.getInt(offset + 3) // pressureValue
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PressureValue entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTestID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPressureTime(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPressureValue(cursor.getInt(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PressureValue entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PressureValue entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PressureValue entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
