package com.thnet.tailairbrakingtest.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SysParms".
*/
public class SysParmsDao extends AbstractDao<SysParms, Long> {

    public static final String TABLENAME = "SysParms";

    /**
     * Properties of entity SysParms.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "id");
        public final static Property ParamID = new Property(1, String.class, "paramID", false, "ParamID");
        public final static Property ParamName = new Property(2, String.class, "paramName", false, "ParamName");
        public final static Property ParamValue = new Property(3, String.class, "paramValue", false, "ParamValue");
        public final static Property ParamIndex = new Property(4, String.class, "paramIndex", false, "ParamIndex");
    }


    public SysParmsDao(DaoConfig config) {
        super(config);
    }
    
    public SysParmsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SysParms entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String paramID = entity.getParamID();
        if (paramID != null) {
            stmt.bindString(2, paramID);
        }
 
        String paramName = entity.getParamName();
        if (paramName != null) {
            stmt.bindString(3, paramName);
        }
 
        String paramValue = entity.getParamValue();
        if (paramValue != null) {
            stmt.bindString(4, paramValue);
        }
 
        String paramIndex = entity.getParamIndex();
        if (paramIndex != null) {
            stmt.bindString(5, paramIndex);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SysParms entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String paramID = entity.getParamID();
        if (paramID != null) {
            stmt.bindString(2, paramID);
        }
 
        String paramName = entity.getParamName();
        if (paramName != null) {
            stmt.bindString(3, paramName);
        }
 
        String paramValue = entity.getParamValue();
        if (paramValue != null) {
            stmt.bindString(4, paramValue);
        }
 
        String paramIndex = entity.getParamIndex();
        if (paramIndex != null) {
            stmt.bindString(5, paramIndex);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public SysParms readEntity(Cursor cursor, int offset) {
        SysParms entity = new SysParms( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // paramID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // paramName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // paramValue
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // paramIndex
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SysParms entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setParamID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setParamName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setParamValue(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setParamIndex(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(SysParms entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(SysParms entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SysParms entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
