package com.thnet.tailairbrakingtest.DAO;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TestWindContent".
*/
public class TestWindContentDao extends AbstractDao<TestWindContent, Long> {

    public static final String TABLENAME = "TestWindContent";

    /**
     * Properties of entity TestWindContent.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "id");
        public final static Property TestID = new Property(1, String.class, "testID", false, "TestID");
        public final static Property TestDate = new Property(2, String.class, "testDate", false, "TestDate");
        public final static Property TrainNo = new Property(3, String.class, "trainNo", false, "TrainNo");
        public final static Property TrainCount = new Property(4, String.class, "trainCount", false, "TrainCount");
        public final static Property SpecifyPressure = new Property(5, String.class, "specifyPressure", false, "SpecifyPressure");
        public final static Property StartTime = new Property(6, String.class, "startTime", false, "StartTime");
        public final static Property EndTime = new Property(7, String.class, "endTime", false, "EndTime");
        public final static Property TestKind = new Property(8, String.class, "testKind", false, "TestKind");
        public final static Property Line = new Property(9, String.class, "line", false, "Line");
        public final static Property UserGroup = new Property(10, String.class, "userGroup", false, "UserGroup");
        public final static Property TestOperator = new Property(11, String.class, "testOperator", false, "TestOperator");
        public final static Property ValveNo = new Property(12, String.class, "valveNo", false, "ValveNo");
    }


    public TestWindContentDao(DaoConfig config) {
        super(config);
    }
    
    public TestWindContentDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TestWindContent entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String testID = entity.getTestID();
        if (testID != null) {
            stmt.bindString(2, testID);
        }
 
        String testDate = entity.getTestDate();
        if (testDate != null) {
            stmt.bindString(3, testDate);
        }
 
        String trainNo = entity.getTrainNo();
        if (trainNo != null) {
            stmt.bindString(4, trainNo);
        }
 
        String trainCount = entity.getTrainCount();
        if (trainCount != null) {
            stmt.bindString(5, trainCount);
        }
 
        String specifyPressure = entity.getSpecifyPressure();
        if (specifyPressure != null) {
            stmt.bindString(6, specifyPressure);
        }
 
        String startTime = entity.getStartTime();
        if (startTime != null) {
            stmt.bindString(7, startTime);
        }
 
        String endTime = entity.getEndTime();
        if (endTime != null) {
            stmt.bindString(8, endTime);
        }
 
        String testKind = entity.getTestKind();
        if (testKind != null) {
            stmt.bindString(9, testKind);
        }
 
        String line = entity.getLine();
        if (line != null) {
            stmt.bindString(10, line);
        }
 
        String userGroup = entity.getUserGroup();
        if (userGroup != null) {
            stmt.bindString(11, userGroup);
        }
 
        String testOperator = entity.getTestOperator();
        if (testOperator != null) {
            stmt.bindString(12, testOperator);
        }
 
        String valveNo = entity.getValveNo();
        if (valveNo != null) {
            stmt.bindString(13, valveNo);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TestWindContent entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String testID = entity.getTestID();
        if (testID != null) {
            stmt.bindString(2, testID);
        }
 
        String testDate = entity.getTestDate();
        if (testDate != null) {
            stmt.bindString(3, testDate);
        }
 
        String trainNo = entity.getTrainNo();
        if (trainNo != null) {
            stmt.bindString(4, trainNo);
        }
 
        String trainCount = entity.getTrainCount();
        if (trainCount != null) {
            stmt.bindString(5, trainCount);
        }
 
        String specifyPressure = entity.getSpecifyPressure();
        if (specifyPressure != null) {
            stmt.bindString(6, specifyPressure);
        }
 
        String startTime = entity.getStartTime();
        if (startTime != null) {
            stmt.bindString(7, startTime);
        }
 
        String endTime = entity.getEndTime();
        if (endTime != null) {
            stmt.bindString(8, endTime);
        }
 
        String testKind = entity.getTestKind();
        if (testKind != null) {
            stmt.bindString(9, testKind);
        }
 
        String line = entity.getLine();
        if (line != null) {
            stmt.bindString(10, line);
        }
 
        String userGroup = entity.getUserGroup();
        if (userGroup != null) {
            stmt.bindString(11, userGroup);
        }
 
        String testOperator = entity.getTestOperator();
        if (testOperator != null) {
            stmt.bindString(12, testOperator);
        }
 
        String valveNo = entity.getValveNo();
        if (valveNo != null) {
            stmt.bindString(13, valveNo);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TestWindContent readEntity(Cursor cursor, int offset) {
        TestWindContent entity = new TestWindContent( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // testID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // testDate
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // trainNo
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // trainCount
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // specifyPressure
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // startTime
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // endTime
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // testKind
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // line
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // userGroup
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // testOperator
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12) // valveNo
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TestWindContent entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTestID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTestDate(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTrainNo(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTrainCount(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setSpecifyPressure(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setStartTime(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setEndTime(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setTestKind(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setLine(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setUserGroup(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setTestOperator(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setValveNo(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TestWindContent entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TestWindContent entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TestWindContent entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
