package com.thnet.tailairbrakingtest.DAO;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TestDetail".
*/
public class TestDetailDao extends AbstractDao<TestDetail, Long> {

    public static final String TABLENAME = "TestDetail";

    /**
     * Properties of entity TestDetail.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "id");
        public final static Property TestID = new Property(1, String.class, "testID", false, "TestID");
        public final static Property TestName = new Property(2, String.class, "testName", false, "TestName");
        public final static Property BeginTime = new Property(3, String.class, "beginTime", false, "BeginTime");
        public final static Property EndTime = new Property(4, String.class, "endTime", false, "EndTime");
        public final static Property TestPressure = new Property(5, String.class, "testPressure", false, "TestPressure");
        public final static Property KeepTime = new Property(6, String.class, "keepTime", false, "KeepTime");
        public final static Property LeakValue = new Property(7, String.class, "leakValue", false, "LeakValue");
        public final static Property DropValue = new Property(8, String.class, "dropValue", false, "DropValue");
        public final static Property DropTime = new Property(9, String.class, "dropTime", false, "DropTime");
        public final static Property DropSpeed = new Property(10, String.class, "dropSpeed", false, "DropSpeed");
        public final static Property State = new Property(11, String.class, "state", false, "State");
    }


    public TestDetailDao(DaoConfig config) {
        super(config);
    }
    
    public TestDetailDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TestDetail entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String testID = entity.getTestID();
        if (testID != null) {
            stmt.bindString(2, testID);
        }
 
        String testName = entity.getTestName();
        if (testName != null) {
            stmt.bindString(3, testName);
        }
 
        String beginTime = entity.getBeginTime();
        if (beginTime != null) {
            stmt.bindString(4, beginTime);
        }
 
        String endTime = entity.getEndTime();
        if (endTime != null) {
            stmt.bindString(5, endTime);
        }
 
        String testPressure = entity.getTestPressure();
        if (testPressure != null) {
            stmt.bindString(6, testPressure);
        }
 
        String keepTime = entity.getKeepTime();
        if (keepTime != null) {
            stmt.bindString(7, keepTime);
        }
 
        String leakValue = entity.getLeakValue();
        if (leakValue != null) {
            stmt.bindString(8, leakValue);
        }
 
        String dropValue = entity.getDropValue();
        if (dropValue != null) {
            stmt.bindString(9, dropValue);
        }
 
        String dropTime = entity.getDropTime();
        if (dropTime != null) {
            stmt.bindString(10, dropTime);
        }
 
        String dropSpeed = entity.getDropSpeed();
        if (dropSpeed != null) {
            stmt.bindString(11, dropSpeed);
        }
 
        String state = entity.getState();
        if (state != null) {
            stmt.bindString(12, state);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TestDetail entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String testID = entity.getTestID();
        if (testID != null) {
            stmt.bindString(2, testID);
        }
 
        String testName = entity.getTestName();
        if (testName != null) {
            stmt.bindString(3, testName);
        }
 
        String beginTime = entity.getBeginTime();
        if (beginTime != null) {
            stmt.bindString(4, beginTime);
        }
 
        String endTime = entity.getEndTime();
        if (endTime != null) {
            stmt.bindString(5, endTime);
        }
 
        String testPressure = entity.getTestPressure();
        if (testPressure != null) {
            stmt.bindString(6, testPressure);
        }
 
        String keepTime = entity.getKeepTime();
        if (keepTime != null) {
            stmt.bindString(7, keepTime);
        }
 
        String leakValue = entity.getLeakValue();
        if (leakValue != null) {
            stmt.bindString(8, leakValue);
        }
 
        String dropValue = entity.getDropValue();
        if (dropValue != null) {
            stmt.bindString(9, dropValue);
        }
 
        String dropTime = entity.getDropTime();
        if (dropTime != null) {
            stmt.bindString(10, dropTime);
        }
 
        String dropSpeed = entity.getDropSpeed();
        if (dropSpeed != null) {
            stmt.bindString(11, dropSpeed);
        }
 
        String state = entity.getState();
        if (state != null) {
            stmt.bindString(12, state);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TestDetail readEntity(Cursor cursor, int offset) {
        TestDetail entity = new TestDetail( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // testID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // testName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // beginTime
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // endTime
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // testPressure
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // keepTime
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // leakValue
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // dropValue
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // dropTime
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // dropSpeed
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11) // state
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TestDetail entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTestID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTestName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setBeginTime(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setEndTime(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setTestPressure(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setKeepTime(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setLeakValue(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setDropValue(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setDropTime(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setDropSpeed(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setState(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TestDetail entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TestDetail entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TestDetail entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
