name: Build Debug APK
on:
  push:
    branches: [ master ]  # 主分支是master就改成master
  workflow_dispatch:

jobs:
  build_debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: gradle

      # 使用官方 setup‑android，同时指定 ndk 版本 21.0.6113669
      - name: Setup Android SDK & NDK
        uses: android-actions/setup-android@v3
        with:
          ndk: '21.0.6113669'

      - name: Grant gradlew execute permission
        run: chmod +x ./gradlew

      - name: Run assembleDebug
        run: ./gradlew assembleDebug

      - name: Upload Debug APKs
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk-all-abi
          path: app/build/outputs/apk/debug/*.APK
